### ISSUE TITLE
vsync: this error

### ISSUE THREAD

**Issue by gotorahul6909** [aman246149/flutter-animations-login#1]
animationController=AnimationController(
      //vsync: this,
      vsync: this, //Getting error in this line
      duration: Duration(seconds: 2),
    );

Error:

'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 243 pos 15: 
'vsync != null': is not true.

**Comment by aman246149** [comment]
can you send me your code

**Comment by aman246149** [comment]
let me know if this fixed your issue
https://github.com/flutter/flutter/issues/36588

**Comment by gotorahul6909** [comment]
import 'dart:developer';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:splashscreen/models/Genders.dart';
import 'package:splashscreen/models/UserInquiry.dart';
import 'package:splashscreen/widgets/GenderSelector.dart';

void main() => runApp(new MaterialApp());

class TestPage extends StatefulWidget {
  @override
  _TestPageState createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  final _formResult = UserInquiry();
  final _birthcontroller = TextEditingController();
  Genders _genders;
  DateTime _birthdatetime;

  AnimationController animationController;
  Animation animation;
  Animation animationleft;
  Animation<Offset> offset;
  Animation<Offset> offset2;

  @override
  initState(){
    super.initState();

    animationController=AnimationController(
      //vsync: this,
      vsync: this,
      duration: Duration(seconds: 2),
    );

    animation=Tween<double>(begin: 1,end: 0).animate(CurvedAnimation(
        parent: animationController,curve: Curves.fastOutSlowIn
    ));

    animationleft=Tween<double>(begin: -1,end: 0).animate(CurvedAnimation(
        parent: animationController,curve: Curves.fastOutSlowIn
    ));

    offset = Tween<Offset>(
        begin: Offset.zero,
        end: Offset(0.0, 1.0)
    ).animate(
        CurvedAnimation(
            parent: animationController,
            curve: Curves.fastLinearToSlowEaseIn)
    );

    offset2 = Tween<Offset>(
      begin: Offset(0.0, 0.1),
      end: Offset.zero
    ).animate(
      CurvedAnimation(
        parent: animationController,
        curve: Curves.fastLinearToSlowEaseIn)
    );

    animationController.addListener(() {
      setState(() {

      });
    });

    animationController.forward();
  }

  @override
  void dispose(){
    super.dispose();
    animationController.dispose();
  }

  _updateGender(Genders selGender){
    _genders = selGender;
    print("Gender Printed");
    print(_genders.name);
  }

  _submitform(){
    final FormState form = _formKey.currentState;
    _formResult.gender = _genders.name;
    if(form.validate()){
      print("Submit Called");
      print(_formResult.toJson());
    }
  }

  @override
  Widget build(BuildContext context) {

    return new Scaffold(
      appBar: new AppBar(
        title: new Text("BMU Law"),
        actions: <Widget>[
          new IconButton(
            icon: new Icon(
                Icons.person,
              color: Colors.white,
            ),
            onPressed: () {},
          ),
        ],
      ),
      drawer: new Drawer(
        child: new ListView(
          children: <Widget>[
            new DrawerHeader(
              child: Image.asset("images/law_bg.png"),
              decoration: new BoxDecoration(
                color: Colors.red
              ),
            ),
            new InkWell(
              onTap: () {},
              child: ListTile(
                title: Text('Contact Us'),
                leading: Icon(Icons.contact_mail,
                  color: Colors.red,),
              ),
            ),
          ],
        ),
      ),
      body: new SafeArea(
        top: false,
        bottom: false,
        child: new Form(
          key: _formKey,
          autovalidate: false,
          child: new ListView(
            padding: const EdgeInsets.symmetric(horizontal: 16.0),
            children: <Widget>[
              new SlideTransition(
                position: offset2,
                child: new Container(
                  child: new Text(
                    "Contact Us",
                    style: new TextStyle(
                      fontSize: 68.0,
                      fontWeight: FontWeight.bold,
                      color: Colors.redAccent
                    ),
                  ),
                ),
              ),
              new SizedBox(height: 8.0,),
              new Text("Name:"),
              new TextFormField(
                decoration: const InputDecoration(
                  hintText: "Enter your name",
                  //labelText: "Name"
                ),
                inputFormatters: [LengthLimitingTextInputFormatter(30)],
                //initialValue: _formResult.name,
                validator: (userName){
                  if(userName.isEmpty){
                    return "Name is required.";
                  }
                  if(userName.length < 3){
                    return "Name is too short.";
                  }
                  return null;
                },
                onChanged: (userName){
                  _formResult.name = userName;
                },
                onSaved: (userName){
                  setState(() {
                    _formResult.name = userName;
                  });
                },
              ),
              new SizedBox(height: 8.0,),
              new Text("Gender:"),
              new GenderSelector(
                selectedGender: _updateGender,
              ),
              new SizedBox(height: 8.0,),
              new Text("DOB:"),
              new TextFormField(
                controller: _birthcontroller,
                readOnly: true,
                //initialValue: _birthdatetime.toString() ?? _birthcontroller.text,
                onTap: () {
                  showDatePicker(
                      context: context,
                      initialDate: DateTime.now(),
                      firstDate: DateTime(1900),
                      lastDate: DateTime.now()
                  ).then((birthDate){
                    setState(() {
                      _birthcontroller.text = DateFormat.yMMMMEEEEd().format(birthDate);//birthDate.toString();
                      _birthdatetime = birthDate;
                      _formResult.birthdate = birthDate;
                    });

                    //return _birthcontroller;
                  });
                },
                validator: (birthDate){
                  if(birthDate.isEmpty){
                    return "DOB is required.";
                  }
                  return null;
                },
                onSaved: (birthDate){
                  print("ffff");
                  _formResult.birthdate = _birthdatetime;
                },
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _submitform,
        tooltip: "Save",
        child: new Icon(
          Icons.check,
          size: 36.0,
        ),
      ),
    );
  }
}

**Comment by aman246149** [comment]
please use SingleTickerProviderStateMixin in your state

that  is instead of
class _TestPageState extends State {

use
class _TestPageState extends State  with SingleTickerProviderStateMixin {

watch carefully this part in my code also ..

Hope this will solve your problem...
